<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Promise</title>
</head>
<body>
  <script>
    //resolve, reject, all, ract
    //resolve == then, reject == catch

    // let promise = new Promise((resolve, reject) => {
    //   // reject();    //失败
    //   resolve(111);   //成功
    // })

    // promise.then(response => {  
    //   console.log('成功');
    //   console.log(response);
    // }).catch(erroe => {
    //   console.log('失败');
    //   console.log(error);
    // })

    // //链式
    function promise1(status) {
      return new Promise((resolve,reject) => {
        if(status){
          console.log('第1个promise成功')
          resolve('第1个promise返回数据成功')
        }
        if(!status) {
          console.log( '第1个promise失败');
          reject("第1个promise返回数据失败")
        }
      })
    }
    function promise2(status) {
      return new Promise((resolve,reject) => {
        if(status){
          console.log('第2个promise成功')
          resolve('第2个promise返回数据成功')
        }
        if(!status) {
          console.log( '第2个promise失败');
          reject("第2个promise返回数据失败")
        }
      })
    }
    function promise3(status) {
      return new Promise((resolve,reject) => {
        if(status){
          console.log('第3个promise成功')
          resolve('第3个promise返回数据成功');
        }
        if(!status) {
          console.log( '第3个promise失败');
          reject("第3个promise返回数据失败");
        }
      })
    }

    // // 每一个都是可分离的，不是嵌套住的
    // promise1(true).then(response => {
    //   console.log(response);
    //   // 返回数据，判断是否执行第2个promise
    //   return promise2(true);
    // }).then(response => {
    //   console.log(response);
    //   return promise3(true);
    // }).then(response => {
    //   console.log(response);
    // }).catch(error => {
    //   console.log(error);
    // })

    // all方法，数组内有promise必须全部成功(全部返回resolve)，才会执行then回调，只要有一个是返回(reject)不成功，就会执行catch
    // Promise.all([promise1(false), promise2(true), promise3(true)]).then(response => {
    //  console.log("全部调用成功");
    // }).catch(error => {
    //  console.log("有些可能失败了");
    // })
    // race数组，当在执行的时候，遇到的返回结果是resolve(成功)，一直执行链式。
    // 最终的理解:race，只要有一个是返回resolve，就代表成功，就会回调then,但是如果第一个是返回reject，则失败。
    Promise.race([promise1(true), promise2(false), promise3(false)]).then(response => {
     console.log("成功");
    }).catch(error => {
     console.log("失败");
    })
 


    // var obj = {
    //   say : function() {
    //     var f1= () =>{
    //       console.log("1111", this) ;
    //     }
    //     f1();
    //   },
    //   pro: {
    //     getPro:() =>{
    //       console.log(this );
    //     }
    //   }
    // }
    // var o = obj.say ;
    // console.log('****************');
    // o();
    // console.log('****************');
    // obj.say();
    // console.log('****************');
    // obj.pro.getPro();


  </script>
</body>
</html>